stages:
- inputs:
  - branch: master
    dir_name: null
    type: git
    service: gitlab00
  jobs:
  - artifact_dir: ""
    name: Build
    type: builder
  name: BUILD
  permission:
    execute: TOOLCHAIN_ADMINS
  triggers:
  - events: '{"push":true,"pull_request":false,"pull_request_closed":false}'
    type: git
- inputs:
  - dir_name: null
    job: Build
    stage: BUILD
    type: job
  jobs:
  - deploy_type: cf
    name: Rolling Deploy
    script: "#!/bin/bash\n# Push app\nif ! cf app \"$CF_APP\"; then  \n  cf push \"$CF_APP\"\nelse\n
      \ OLD_CF_APP=\"${CF_APP}-OLD-$(date +\"%s\")\"\n  rollback() {\n    set +e  \n
      \   if cf app \"$OLD_CF_APP\"; then\n      cf logs \"$CF_APP\" --recent\n      cf
      delete \"$CF_APP\" -f\n      cf rename \"$OLD_CF_APP\" \"$CF_APP\"\n    fi\n
      \   exit 1\n  }\n  set -e\n  trap rollback ERR\n  cf rename \"$CF_APP\" \"$OLD_CF_APP\"\n
      \ cf push \"$CF_APP\"\n  cf delete \"$OLD_CF_APP\" -f\nfi\n# Export app name
      and URL for use in later Pipeline jobs\nexport CF_APP_NAME=\"$CF_APP\"\nexport
      APP_URL=http://$(cf app $CF_APP_NAME | grep -e urls: -e routes: | awk '{print
      $2}')\n# View logs\n#cf logs \"${CF_APP}\" --recent\n"
    target:
      api_key: nzcm0FKVBy+6CsXjeeyXnLa130+66g0gDwGB9QGtT/yV5mftzARguOrjf+47LOi0QivgI3QCx+70jKTkn0K4zQ==
      application: CF-TEMPLATE
      organization: eric_jodet@fr.ibm.com
      region_id: ibm:ys1:us-south
      space: dev
    type: deployer
  name: DEPLOY
  permission:
    execute: TOOLCHAIN_ADMINS
  properties:
  - name: CF_APP_NAME
    type: text
    value: undefined
  - name: APP_URL
    type: text
    value: undefined
  triggers:
  - type: stage
properties: []
