stages:
- inputs:
  - branch: master
    dir_name: null
    type: git
    service: sample-repo
  jobs:
  - artifact_dir: ""
    name: Build
    type: builder
  name: BUILD
  properties:
  - name: BUILD_TEXT_PROP
    type: text
    value: toto
  - name: BUILD_SECURE_PROP
    type: secure
  triggers:
  - type: commit
- inputs:
  - dir_name: null
    job: Build
    stage: BUILD
    type: job
  jobs:
  - deploy_permission: DEV_IN_SPACE
    deploy_type: cf
    name: Deploy
    script: |
      #!/bin/bash
      # Push app
      export CF_APP_NAME="$CF_APP"
      cf push "${CF_APP_NAME}"
      export APP_URL=http://$(cf app $CF_APP_NAME | grep -e urls: -e routes: | awk '{print $2}')
      # View logs
      #cf logs "${CF_APP_NAME}" --recent
    target:
      application: simple-toolchain-20200417053340826
      organization: eric_jodetfribmcom
      region_id: w3ibm:prod:us-south
      space: dev
    type: deployer
  name: DEPLOY
  properties:
  - name: CF_APP_NAME
    type: text
    value: undefined
  - name: APP_URL
    type: text
    value: undefined
  - name: DEPLOY_SECRURE_PROP
    type: secure
  triggers:
  - type: stage
properties: null
